# @package _group_

_target_: src.algos.mopo.MOPO

reward_penalty_coef: 0.0

# These are parameters passed to the MOPO object via **cfg.mopo.mopo_params
mopo_params:
  max_epoch: 400
  rollout_batch_size: 50000
  rollout_mini_batch_size: 10000
  rollout_length: 5  # This is the length of the rollout used in model training
  model_retain_epochs: 1
  num_env_steps_per_epoch: 1000
  train_model_interval: 250
  max_trajectory_length: 1000
  eval_interval: 1000
  num_eval_trajectories: 10
  snapshot_interval: 2000
  model_env_ratio: 0.95
  max_model_update_epochs_to_improve: 5
  max_model_train_iterations: null  # replaces "None"
